[package]
name = "enucleate"
version = "0.1.0"
edition = "2018"
authors = ["Martin Pool"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.6"
quote = "1.0"
similar = "2.0"

[dependencies.syn]
version = "1.0.76"
features = ["full", "extra-traits", "visit", "visit-mut"]

[dependencies.proc-macro2]
features = ["span-locations"]
version = "1.0.29"

[dev-dependencies]
pretty_assertions = "0.7.2"
