[package]
name = "enucleate"
version = "0.1.0"
edition = "2018"
authors = ["Martin Pool"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.6"
atty = "0.2"
console = "0.14"
itertools = "0.10"
path-slash = "0.1.4"
quote = "1.0"
similar = "2.0"
tempfile = "3.2"
walkdir = "2.3"

[dependencies.cp_r]
version = "0.2"
# path = "../cp_r"

[dependencies.syn]
version = "1.0.76"
features = ["full", "extra-traits", "visit"]

[dependencies.proc-macro2]
features = ["span-locations"]
version = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0"
insta = "1.8"
lazy_static = "1.4"
predicates = "2.0"
pretty_assertions = "0.7.2"
regex = "1.5"
