[package]
name = "enucleate"
version = "0.1.0"
edition = "2018"
authors = ["Martin Pool"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.6"
copy_dir = "0.1.2"
path-slash = "0.1.4"
quote = "1.0"
similar = "2.0"
tempdir = "0.3"
walkdir = "2.3"

[dependencies.syn]
version = "1.0.76"
features = ["full", "extra-traits", "visit"]

[dependencies.proc-macro2]
features = ["span-locations"]
version = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0"
lazy_static = "1.4"
pretty_assertions = "0.7.2"
