[package]
name = "enucleate"
version = "0.1.0"
edition = "2018"
authors = ["Martin Pool"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
syntex_syntax = "0.59"
