name: actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - "!.github/workflows/release.yml" # generated
  push:
    paths:
      - ".github/workflows/*.yml"
      - "!.github/workflows/release.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  action-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: devops-actions/actionlint@v0.1.2
        id: action-lint

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: actionlint-results
          path: ${{ steps.action-lint.outputs.results-file }}
