name: cargo-audit

on:
  schedule:
    - cron: "17 0 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - .github/workflows/cargo-audit.yml

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo-audit
        run: |
          cargo install cargo-audit
          cargo audit --ignore RUSTSEC-2021-0139

# Ignore RUSTSEC-2021-0139, ansi_term is unmaintained, there's no obvious security issue.
