name: MSRV

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

# see https://matklad.github.io/2021/09/04/fast-rust-builds.html
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10
  CARGO_MUTANTS_MINIMUM_TEST_TIMEOUT: 60

jobs:
  test:
    strategy:
      matrix:
        toolchain: ["1.65"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Show Cargo and rustc version
        run: |
          cargo +${{ matrix.toolchain }} --version
          rustc +${{ matrix.toolchain }} --version
      - name: Test
        run: cargo +${{ matrix.toolchain }} test --workspace
